name: 'MyWorkflow2'

on:
    push:
        branches:
          - master
        tags:
          - '[0-9].+[0-9].+[0-9]'

jobs:
    deploy:
      runs-on: ubuntu-latest

  
      steps: 
        - name: Checkout to project repository
          uses: actions/checkout@v3
          with:
            repository: Avagyan02/Github_action_task
            ref: main
            token: ${{ secrets.PERSONAL_TOKEN }}

        - name: Configure AWS credentials
          uses: aws-actions/configure-aws-credentials@v2
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: eu-central-1

        - name: Get commit hash
          id: get_commit_hash
          run: echo "::set-output name=commit_hash::$(git rev-parse --short HEAD)"


        - name: Initialize Terraform
          uses: hashicorp/setup-terraform@v1
          with:
            terraform_version: 1.0.0
    
        - name: Terraform apply
          run: |
            terraform init
            terraform apply -auto-approve -var "commit_hash=${{ steps.get_commit_hash.outputs.commit_hash }}"
